### ISSUE TITLE
TapableLabel doesn't respond to tap delegate when matched string is neither phone number or link.

### ISSUE THREAD

**Issue by mohsinka** [qiuncheng/CuteAttribute#4]
I am trying to underline and highlight a certain text and use tapableLabel. However when I set cuteAttributes to certain text in the label and desire to tap it, it doesn't call the delegate method despite the label being the delegate of the view controller. Please let me know what I am doing wrong.

<img width="717" alt="screen shot 2018-05-20 at 2 12 49 pm" src="https://user-images.githubusercontent.com/6949964/40276263-f97ee8da-5c37-11e8-8421-afcb193d2e9a.png">

**Comment by status302** [comment]
Hello @mohsinka , is indicatorLbl frame's height equal to content height?

**Comment by status302** [comment]
Hello @mohsinka , could you provide a screenshot for indicatorLbl's constraints in Storyboard?

**Comment by mohsinka** [comment]
Hello so here are the constraints:

<img width="1166" alt="screen shot 2018-05-22 at 5 21 22 pm" src="https://user-images.githubusercontent.com/6949964/40353693-aeea4482-5de4-11e8-828b-fd7910766983.png">

**Comment by status302** [comment]
Hello, could you remove the height constraint and try ?

**Comment by mohsinka** [comment]
Awesome! It did the trick for me. Thank you so much!

**Comment by status302** [comment]
Hi @mohsinka, I make it that it will response to tap action whether you had set the height constraint for label or not. 😃

**Comment by mohsinka** [comment]
@qiuncheng cool, i'll take the update and check :)
