### ISSUE TITLE
lack of NSBackgroundColorAttributeName ?

### ISSUE THREAD

**Issue by change2hao** [qiuncheng/CuteAttribute#5]
I couldn't find the 'NSBackgroundColorAttributeName' attribute, could you add it?

**Comment by status302** [comment]
@change2hao Are you using Swift 4.2 now?

**Comment by status302** [comment]
use `color(_:)`.

**Comment by change2hao** [comment]
> use `color(_:)`.

this is foregroundColor，my meaning is backgroundColor

**Comment by status302** [comment]
support now.

**Comment by change2hao** [comment]
> support now.

pod search always 1.2.0

**Comment by status302** [comment]
我这边可以啊，你试试 pod repo update 再search
